// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // O CLI (migrate, studio, db pull) usa esta conexão. Com Supabase, aponte
  // para o pooler em modo "session" (DIRECT_URL) — o modo "transaction" não
  // suporta os advisory locks que o Migrate precisa. Provedores sem pooler
  // (ex: Neon) não definem DIRECT_URL, então cai para DATABASE_URL.
  // O client em runtime (src/lib/prisma.ts) sempre usa DATABASE_URL direto,
  // via driver adapter, independente desta configuração.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
